<a href="https://colab.research.google.com/github/divyaseri/divya_INFO5731_Fall2020/blob/master/In_class_exercise_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **The second In-class-exercise (9/9/2020, 20 points in total)**


(1) Write a Python program to find the duplicate elements in a given array of integers. Return -1 If there are no such elements. (4 points)

In [ ]:
#create an array
array1 = [6,9,7,1,2,4,5,8,3]
dup_arr = -1 
#for displaying dup elements in the array
for i in range(0,len(array1)):
    for j in range(i+1, len(array1)): 
        if array1[i] == array1[j]:
            if array1[i] not in dup_arr:
                dup_arr.append(array1[i])
print(dup_arr)


-1


(2) Write a Python program to select all the Sundays of a specified year. (4 points)



In [ ]:

from datetime import date, timedelta
year = 2020
#start date
sun = date(year, 1, 1)
# first sunday
sun += timedelta(days = 6 - sun.weekday())
print(sun)
while sun.year == year:
    sun += timedelta(days = 7)
    print(sun)

2020-01-05
2020-01-12
2020-01-19
2020-01-26
2020-02-02
2020-02-09
2020-02-16
2020-02-23
2020-03-01
2020-03-08
2020-03-15
2020-03-22
2020-03-29
2020-04-05
2020-04-12
2020-04-19
2020-04-26
2020-05-03
2020-05-10
2020-05-17
2020-05-24
2020-05-31
2020-06-07
2020-06-14
2020-06-21
2020-06-28
2020-07-05
2020-07-12
2020-07-19
2020-07-26
2020-08-02
2020-08-09
2020-08-16
2020-08-23
2020-08-30
2020-09-06
2020-09-13
2020-09-20
2020-09-27
2020-10-04
2020-10-11
2020-10-18
2020-10-25
2020-11-01
2020-11-08
2020-11-15
2020-11-22
2020-11-29
2020-12-06
2020-12-13
2020-12-20
2020-12-27
2021-01-03


(3) Python files reading and writing. Download the “[exercise_02_data _collection.zip](https://github.com/unt-iialab/INFO5731_FALL2020/blob/master/In_class_exercise/exercise_02_data_collection.zip)” to your local and un-zip it.

*   Write a program to read all the txt files and save the sentences in all the files into one csv file with two columns, the first column is sentence id (txt file name+sentence line number), the second column is the sentence text content. (4 points)
*   Remove all the punctuations from the sentences, save the processed sentences into a new column in the same csv file. (4 points)
*   Ask the user to enter a word, return all the sentences that include this word, three kinds of information should be returned: sentence id, sentence text content, the count that user input word appear in the sentence. (4 points)



In [2]:
from google.colab import files
uploaded = files.upload()

Saving ARTHROTEC.1.txt to ARTHROTEC.1.txt
Saving ARTHROTEC.2.txt to ARTHROTEC.2.txt
Saving ARTHROTEC.3.txt to ARTHROTEC.3.txt
Saving ARTHROTEC.4.txt to ARTHROTEC.4.txt
Saving ARTHROTEC.5.txt to ARTHROTEC.5.txt
Saving ARTHROTEC.6.txt to ARTHROTEC.6.txt
Saving ARTHROTEC.7.txt to ARTHROTEC.7.txt
Saving ARTHROTEC.8.txt to ARTHROTEC.8.txt
Saving ARTHROTEC.9.txt to ARTHROTEC.9.txt
Saving ARTHROTEC.10.txt to ARTHROTEC.10.txt
Saving ARTHROTEC.11.txt to ARTHROTEC.11.txt
Saving ARTHROTEC.12.txt to ARTHROTEC.12.txt
Saving ARTHROTEC.13.txt to ARTHROTEC.13.txt
Saving ARTHROTEC.14.txt to ARTHROTEC.14.txt
Saving ARTHROTEC.15.txt to ARTHROTEC.15.txt
Saving ARTHROTEC.16.txt to ARTHROTEC.16.txt
Saving ARTHROTEC.17.txt to ARTHROTEC.17.txt
Saving ARTHROTEC.18.txt to ARTHROTEC.18.txt
Saving ARTHROTEC.19.txt to ARTHROTEC.19.txt
Saving ARTHROTEC.20.txt to ARTHROTEC.20.txt
Saving ARTHROTEC.21.txt to ARTHROTEC.21.txt
Saving ARTHROTEC.22.txt to ARTHROTEC.22.txt
Saving ARTHROTEC.23.txt to ARTHROTEC.23.txt
Saving

In [3]:
import pandas as pd
sentence_id = []
sentence = []
for files in uploaded:
  with open(files, 'r') as file:
    content = file.read()
    split_content = content.splitlines()
    for line_number in range(len(split_content)):
      sentence_id.append(files + '_' +str(line_number))
      sentence.append(split_content[line_number])
df = pd.DataFrame(list(zip(sentence_id, sentence)), 
               columns =['Sentence ID', 'Sentence'])
df.to_csv('output_file.csv', index = False)

In [4]:

import string
df['After Punctuation Removal'] = df['Sentence'].apply(lambda x:''.join([i for i in x 
                                                  if i not in string.punctuation]))
df.to_csv('output_file.csv', index = False)
df

Sentence ID  ...                          After Punctuation Removal
0      ARTHROTEC.1.txt_0  ...  I feel a bit drowsy  have a little blurred vis...
1      ARTHROTEC.1.txt_1  ...  Ive been on Arthrotec 50 for over 10 years on ...
2      ARTHROTEC.1.txt_2  ...  Due to my arthritis getting progressively wors...
3      ARTHROTEC.1.txt_3  ...  every day for the next month to see how I get ...
4      ARTHROTEC.1.txt_4  ...  So far its been very good pains almost gone bu...
..                   ...  ...                                                ...
530  ARTHROTEC.100.txt_3  ...                           canker sores in my mouth
531  ARTHROTEC.100.txt_4  ...                                           headache
532  ARTHROTEC.100.txt_5  ...            been off for 1 week still have bleeding
533  ARTHROTEC.100.txt_6  ...                               helped my pain alot 
534  ARTHROTEC.100.txt_7  ...                 too scared to take this drug again

[535 rows x 3 columns]

In [5]:
word_2_search = input("Please enter word to search")
result_df =df[df['Sentence'].str.contains(word_2_search,na=False)]
final_df = result_df[['Sentence ID', 'Sentence']]
final_df['Count of Occurance'] = df['Sentence'].apply(lambda x: x.count(word_2_search))
final_df

Please enter word to searchpill


Sentence ID  ... Count of Occurance
23     ARTHROTEC.5.txt_2  ...                  1
24     ARTHROTEC.5.txt_3  ...                  1
27     ARTHROTEC.6.txt_0  ...                  1
28     ARTHROTEC.6.txt_1  ...                  1
29     ARTHROTEC.6.txt_2  ...                  1
80    ARTHROTEC.16.txt_5  ...                  1
84    ARTHROTEC.16.txt_9  ...                  1
111   ARTHROTEC.20.txt_0  ...                  1
116   ARTHROTEC.20.txt_5  ...                  1
123   ARTHROTEC.22.txt_1  ...                  1
130   ARTHROTEC.23.txt_5  ...                  1
132   ARTHROTEC.24.txt_0  ...                  2
138   ARTHROTEC.24.txt_6  ...                  1
151   ARTHROTEC.27.txt_1  ...                  1
189   ARTHROTEC.32.txt_0  ...                  1
202   ARTHROTEC.36.txt_0  ...                  1
207   ARTHROTEC.37.txt_0  ...                  1
211   ARTHROTEC.37.txt_4  ...                  1
212   ARTHROTEC.37.txt_5  ...                  1
240   ARTHROTEC.42.txt_1  ...                  1
243   ARTHROTEC.42.txt_4  ...                  1
277   ARTHROTEC.49.txt_0  ...                  1
295   ARTHROTEC.52.txt_2  ...                  1
298   ARTHROTEC.53.txt_0  ...                  1
303   ARTHROTEC.55.txt_2  ...                  1
304   ARTHROTEC.55.txt_3  ...                  1
307   ARTHROTEC.56.txt_2  ...                  1
315   ARTHROTEC.58.txt_3  ...                  1
319   ARTHROTEC.59.txt_3  ...                  1
326   ARTHROTEC.60.txt_0  ...                  1
330   ARTHROTEC.60.txt_4  ...                  1
357   ARTHROTEC.63.txt_2  ...                  1
450   ARTHROTEC.84.txt_1  ...                  1
465  ARTHROTEC.85.txt_13  ...                  1
472   ARTHROTEC.87.txt_1  ...                  1
482   ARTHROTEC.90.txt_0  ...                  1
506   ARTHROTEC.96.txt_0  ...                  1
521   ARTHROTEC.99.txt_0  ...                  1

[38 rows x 3 columns]

(4) Install packages nltk, numpy, scipy, pandas, and sklearn on Google Colab. Write a program to test whether they are installed successfully. (3 points for extra)

In [7]:
#install packages
! pip install nltk
! pip install numpy
! pip install scipy
! pip install pandas
! pip install scikit-learn

In [20]:
# test nltk
from nltk.tokenize import TweetTokenizer
tknzr = TweetTokenizer()
s0 = "This a new beginning: Hello :-)"
print(tknzr.tokenize(s0))

['This', 'a', 'new', 'beginning', ':', 'Hello', ':-)']


In [19]:
#test numpy
import numpy as np
random_sample = np.random.random_sample()
print(random_sample)


0.2237439882454022


In [21]:
# test scipy
import numpy as np
from scipy.optimize import minimize
def rosen(x):
  """The Rosenbrock function"""
  return sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (1-x[:-1])**2.0)
x0 = np.array([1.3, 0.7, 0.8, 1.9, 1.2])
res = minimize(rosen, x0, method='nelder-mead', options={'xatol': 1e-8, 'disp': True})
print(res)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 339
         Function evaluations: 571
 final_simplex: (array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.00000001, 1.00000001],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 0.99999999]]), array([4.86115343e-17, 7.65182843e-17, 8.11395684e-17, 8.63263255e-17,
       8.64080682e-17, 2.17927418e-16]))
           fun: 4.861153433422115e-17
       message: 'Optimization terminated successfully.'
          nfev: 571
           nit: 339
        status: 0
       success: True
             x: array([1., 1., 1., 1., 1.])


In [24]:
# test pandas
import pandas as pd
d = {'col1': [6, 7], 'col2': [8, 9]}
df = pd.DataFrame(data=d)
print(df)

   col1  col2
0     6     8
1     7     9


In [25]:
# test scikit-learn
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
